workflows:
  android_release:
    name: Build APK (OSM)
    # usa a máquina Linux gratuita
    instance_type: linux
    max_build_duration: 60

    environment:
      flutter: stable
      vars:
        APP_DIR: app

    cache:
      cache_paths:
        - ~/.pub-cache
        - $APP_DIR/build

    scripts:
      - name: Versões das ferramentas
        script: |
          flutter --version
          dart --version
          java -version

      # cria um app Flutter "vazio" num diretório temporário
      - name: Criar esqueleto Flutter
        script: |
          rm -rf $APP_DIR
          flutter create $APP_DIR

      # injeta seus arquivos do repositório (apenas estes dois)
      - name: Injetar arquivos do app
        script: |
          cp -f ci/pubspec.yaml $APP_DIR/pubspec.yaml
          mkdir -p $APP_DIR/lib
          cp -f ci/lib_main.dart $APP_DIR/lib/main.dart
          # Observação: NÃO copiamos nada de android/.
          # Usamos tudo que o "flutter create" gerou.

      - name: Instalar dependências
        script: |
          cd $APP_DIR
          flutter pub get

      - name: Build APK release
        script: |
          cd $APP_DIR
          flutter build apk --release --verbose

    artifacts:
      - $APP_DIR/build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - luishenriquee7@gmail.com
