name: territorios_urbanos
description: App para demarcar territórios em qualquer cidade (OSM). Exporta GeoJSON/KML/KMZ/WKT/GPX. Offline via cache de tiles.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # versões compatíveis entre si
  flutter_map: ^6.1.0
  latlong2: ^0.8.1
  flutter_map_tile_caching: ^8.0.0

  # Utilidades
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.1.3
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  file_picker: ^8.0.3
  http: ^0.13.5
  collection: ^1.18.0
  geojson_vi: ^2.0.4
  xml: ^6.5.0
  archive: ^3.6.1
  gpx: ^2.2.1

flutter:
  uses-material-design: true
